version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=America/Sao_Paulo
    depends_on:
      - db
    networks:
      - juareznet

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - juareznet
    ports:
      - "5432:5432"
    command: postgres -c max_connections=500 -c shared_buffers=512MB

volumes:
  postgres_data:

networks:
  juareznet:
    driver: bridge
