version: "3.8"

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: siqueira-postgres-dev
    environment:
      POSTGRES_DB: siqueira_imoveis_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - siqueira-dev-network
    restart: unless-stopped

  # Redis for Development
  redis-dev:
    image: redis:7-alpine
    container_name: siqueira-redis-dev
    ports:
      - "6380:6379"
    networks:
      - siqueira-dev-network
    restart: unless-stopped

  # Next.js Development Server
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: siqueira-app-dev
    environment:
      DATABASE_URL: postgresql://dev:devpassword@postgres-dev:5432/siqueira_imoveis_dev
      REDIS_URL: redis://redis-dev:6379
      NEXTAUTH_SECRET: dev-secret-key-not-for-production
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres-dev
      - redis-dev
    networks:
      - siqueira-dev-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # Prisma Studio for Development
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: siqueira-prisma-studio
    command: npx prisma studio --port 5555
    environment:
      DATABASE_URL: postgresql://dev:devpassword@postgres-dev:5432/siqueira_imoveis_dev
    ports:
      - "5555:5555"
    depends_on:
      - postgres-dev
    networks:
      - siqueira-dev-network
    volumes:
      - .:/app

volumes:
  postgres_dev_data:
    driver: local

networks:
  siqueira-dev-network:
    driver: bridge
